### ISSUE TITLE
Allow multiple entries in \codefall response

### ISSUE THREAD

**Issue by thmanwithnoname** [TwistedPear-AT/pearbot#2]
Would it be possible to have a modifier on the \codefall command to release more than one key at a time? Like, '\codefall 5' would drop five codes into chat. I like to post codes, but I can't drop more than one at a time, because twitch won't let me repeat the command. (Spam protection, I assume)

This may not be the right way to do this, but I'm not sure where else to ask, so if I screwed up, I'm sorry.

**Comment by pyrige** [comment]
Don't worry, you've come to the right place.
I guess I can add something like that easily enough, I'll probably look into it over the weekend.
I'll still add a limit (thinking 3 or 5) so the output isn't too spammy and cluttered (and people don't accidentally post all their codes.)
