### ISSUE TITLE
can't sign in to pump19 invalid csrf token

### ISSUE THREAD

**Issue by coolbond1** [TwistedPear-AT/pearbot#6]
when i try to sign in through twitch i get the error 401 "invalid csrf token", i would appreciate it if you guys could fix it

**Comment by pyrige** [comment]
There indeed appear to be some issues. I guess I might have missed some API change.
I'll try to get it working again one of these days

**Comment by pyrige** [comment]
We should be using the new API now, please try logging in again if you get the chance

**Comment by coolbond1** [comment]
i still get the error

**Comment by pyrige** [comment]
From what the internet tells me, this might be an issue with your Twitch session/cookies/cache. I reset all the sessions on our end, but you might have to **clear your cache/cookies** for Twitch as well. You could also try linking your account in **Incognito** mode

**Comment by coolbond1** [comment]
clearing the cache and cookies worked great

**Comment by pyrige** [comment]
neat
if only all issues were that easy to solve
